### ISSUE TITLE
Documentation for -b command describes default value incorrectly.

### ISSUE THREAD

**Issue by nealmcb** [solovyevn/pyvenvwrapper#4]
The documentation for the `-b` option says:

> `-b, --python <python executable>`     Use provided Python executable for new virtual environment. <python executable>  should be a path pointing to a Python  interpreter executable file. Works only  with "venv" and "virtualenv". By  default the system's "python" is used.

On my system (Ubuntu Bionic 18.04 LTS), `python` is Python version 2, and `python3` is used for Python version 3. But omitting the `-b` option results in a venv for Python 3. That's actually what I want, but the documentation should be fixed to reflect how it actually works, reminding me that I can just omit the option.

**Comment by solovyevn** [comment]
Are you sure you haven't run the command from an active virtual environment?
Do you have something like Anaconda installed on your machine?
Please, execute these commands in your terminal `python --version` and `which python` and provide the output.
Also, please, show the exact command you executed to create your virtual environment and what underlying tool was used for virtual environment creation. (To see the default tool, execute `mkvenv -h` and look at what's written after `====` signs line, there's a usage explanation for the underlying tool.)

**Comment by nealmcb** [comment]
I'm not running `mkvenv` from inside a virtual environment, though I do remember being confused by other effects of that at one point.

I don't have Anaconda

Here is the command output:

```
$ python --version                                                         
Python 2.7.15rc1                                                                                                         
$ which python                    
/usr/bin/python                                                                                                          
$ mkvenv test-issue-4                                  
mkvenv: Starting...                                                                                                      
mkvenv: Creating virtual environment "test-issue-4" in "/home/neal/Envs/test-issue-4" using "pyvenv"...                  
WARNING: the pyenv script is deprecated in favour of `python3.6 -m venv`      
mkvenv: Virtual environment "test-issue-4" is created. You can activated it using "workon test-issue-4" command, and then
 deactivate using "deact" command.                                           
mkvenv: Skipping project directory creation, because PYVENVWRAPPER_PROJ_DIR variable is not set.        
mkvenv: Done.                                                                                                            
$ workon test-issue-4             
(test-issue-4) $ which python
/home/neal/Envs/test-issue-4/bin/python
(test-issue-4) $ python                                                    
Python 3.6.7 (default, Oct 22 2018, 11:32:17)                                                                            
[GCC 8.2.0] on linux                                                                                                     
Type "help", "copyright", "credits" or "license" for more information.   
...

$ mkvenv -h
...
Help text for underlying utility to use for virtual environment creation is displayed below, you can provide options to
it as a string in quotes via -o option of mkvenv.
================================================================================
usage: venv [-h] [--system-site-packages] [--symlinks | --copies] [--clear]
            [--upgrade] [--without-pip] [--prompt PROMPT]
            ENV_DIR [ENV_DIR ...]

```

**Comment by solovyevn** [comment]
Thank you!
It's not the case for `-b` option.
You have `pyvenv` tool on your system, which was used for virtual environment creation.
As a side note the `-b` option's help string says 'Works only with "venv" and "virtualenv".'.
As for the whole situation, I see it this way:
- Your default Python is 2.7, which doesn't have `venv` module, so this tool wasn't chosen.
- Then `pyvenv` was tried and the `pyvenvwrapper` has found it and used it. (`virtualenv` tool wasn't even looked up, because of this.)
- The `pyvenv` command uses Python 3 by default.

Therefore when a new environment was created, it was created with Python 3 because of the way `pyvenv` itself works.
I believe this is not a bug, nor the `-b` option documentation is incorrect.
Just in case, if you will need to force the usage of some particular tool in the future, then there's the `-u` option for that.

**Comment by nealmcb** [comment]
Thank you for the clarifications. I'm still confused by the documentation, and suggest that instead of

> By default the system's "python" is used.

it say something like

> The default executable is Python 3 if the underlying command used is`pyvenv`, and the system's "python" otherwise.

**Comment by solovyevn** [comment]
There're several points with the whole issue:
1. Actual behavior depends on the underlying tool, so writing something like this in the pyvenvwrapper documentation would make it depend on that tool version more heavily. What if that tool would change its behavior and not use Python 3 anymore - this would require to change the pyvenvwrapper documentation once again.
2. The pyvenv tool itself is actually deprecated.

I believe it doesn't worth it to make a new release just to change this doc.
But thank you for the suggestion, I will consider it when creating future releases.

**Comment by nealmcb** [comment]
Well, how about just saying the default depends on the underlying command? As it is, the documentation is simply wrong in many environments.

**Comment by solovyevn** [comment]
That wouldn't be quite right for all the cases.
You see, the case you're talking about is the case for `pyvenv`, but the `-b` option documentation already says 'Works only with "venv" and "virtualenv".', which means that this option doesn't relate to `pyvevn` in any way.
